# Generated by Django 4.0 on 2021-12-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_id', models.TextField()),
                ('agreement_name', models.TextField()),
                ('client_name', models.TextField()),
                ('client_user_name', models.TextField()),
                ('host_name', models.TextField()),
                ('host_user_name', models.TextField()),
                ('mail_address', models.TextField()),
                ('client_agreement_date', models.TextField()),
                ('host_agreement_date', models.TextField()),
                ('file_name', models.FileField(upload_to='pdf/')),
            ],
        ),
    ]
