# Generated by Django 4.0.5 on 2022-06-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Base',
        ),
        migrations.AddField(
            model_name='list',
            name='agreement_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='client_agreement_date',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='client_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='client_user_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='file_name',
            field=models.FileField(default='', upload_to='pdf/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='host_agreement_date',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='host_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='host_user_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='mail_address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
